<?php
$categories =[
['category' =>'অনুবাদ', 'category_slug' => '', 'description' => ''],
['category' => 'অমর একুশে গ্রন্থমেলা', 'category_slug' => '', 'description' => ''],
['category' => 'অলিম্পিয়াড', 'category_slug' => '', 'description' => ''],
['category' => 'আইন ও বিচার', 'category_slug' => '', 'description' => ''],
['category' => 'আত্ম-উন্নয়ন, মোটিভেশনাল ও মেডিটেশন', 'category_slug' => '', 'description' => ''],
['category' => 'বিশ্ববিদ্যালয় ও কলেজ', 'category_slug' => '', 'description' => ''],
['category' => 'ইঞ্জিনিয়ারিং ও টেকনিক্যাল', 'category_slug' => '', 'description' => ''],
['category' => 'ইতিহাস ও ঐতিহ্য', 'category_slug' => '', 'description' => ''],
['category' => 'উপন্যাস', 'category_slug' => '', 'description' => ''],
['category' => 'কৃষি ও কৃষক বৃত্তান্ত', 'category_slug' => '', 'description' => ''],
['category' => 'কমিক্স,নকশা ও ছবির গল্প', 'category_slug' => '', 'description' => ''],
['category' => 'খেলাধুলা বিষয়ক', 'category_slug' => '', 'description' => ''],
['category' => 'গণমাধ্যম ও সাংবাদিকতা বিষয়ক', 'category_slug' => '', 'description' => ''],
['category' => 'কম্পিউটার,ইন্টারনেট, ফ্রিল্যান্সিং ও আউটসোর্সিং', 'category_slug' => '', 'description' => ''],
['category' => 'গণিত,বিজ্ঞান ও প্রযুক্তি বিষয়ক', 'category_slug' => '', 'description' => ''],
['category' => 'ভূগোল ও পরিবেশ বিদ্যা', 'category_slug' => '', 'description' => ''],
['category' => 'গল্প', 'category_slug' => '', 'description' => ''],
['category' => 'ছড়া,কবিতা ও আবৃত্তি', 'category_slug' => '', 'description' => ''],
['category' => 'জীবনী,স্মৃতিচারণ ও সাক্ষাৎকার', 'category_slug' => '', 'description' => ''],
['category' => 'ড্রয়িং,পেইন্টিং ডিজাইন ও ফটোগ্রাফি', 'category_slug' => '', 'description' => ''],
['category' => 'দর্শন', 'category_slug' => '', 'description' => ''],
['category' => 'ধর্মীয় বই', 'category_slug' => '', 'description' => ''],
['category' => 'ইসলামী বই', 'category_slug' => '', 'description' => ''],
['category' => 'নাটকের বই', 'category_slug' => '', 'description' => ''],
['category' => 'পরিবার,প্যারেন্টিং ও শিশু বিষয়ক', 'category_slug' => '', 'description' => ''],
['category' => 'পরিবেশ ও প্রকৃতি', 'category_slug' => '', 'description' => ''],
['category' => 'পশ্চিমবঙ্গের বই', 'category_slug' => '', 'description' => ''],
['category' => 'পুরষ্কার প্রাপ্ত বই', 'category_slug' => '', 'description' => ''],
['category' => 'প্রফেশনাল,জার্নাল ও রেফারেন্স', 'category_slug' => '', 'description' => ''],
['category' => 'প্রবন্ধ', 'category_slug' => '', 'description' => ''],
['category' => 'প্রসেসিং', 'category_slug' => '', 'description' => ''],
['category' => 'প্রাণী ও জীবজগৎ', 'category_slug' => '', 'description' => ''],
['category' => 'প্রিঅর্ডার', 'category_slug' => '', 'description' => ''],
['category' => 'ফ্যাশন', 'category_slug' => '', 'description' => ''],
['category' => 'ম্যাগাজিন', 'category_slug' => '', 'description' => ''],
['category' => 'বিবিধ', 'category_slug' => '', 'description' => ''],
['category' => 'বাংলাদেশ', 'category_slug' => '', 'description' => ''],
['category' => 'ফিকশন', 'category_slug' => '', 'description' => ''],
['category' => 'নন ফিকশন', 'category_slug' => '', 'description' => ''],
['category' => 'বেস্ট সেলার বুকস', 'category_slug' => '', 'description' => ''],
['category' => 'ব্যঙ্গ ও রম্যরচনা', 'category_slug' => '', 'description' => ''],
['category' => 'ব্যবসা,বিনিয়োগ ও অর্থনীতি', 'category_slug' => '', 'description' => ''],
['category' => 'ভর্তি পরীক্ষার প্রস্তুতি', 'category_slug' => '', 'description' => ''],
['category' => 'বিসিএস', 'category_slug' => '', 'description' => ''],
['category' => 'নিয়োগ পরীক্ষার প্রস্তুতি', 'category_slug' => '', 'description' => ''],
['category' => 'একাডেমিক', 'category_slug' => '', 'description' => ''],
['category' => 'স্কলারশীপ পরীক্ষার প্রস্তুতি', 'category_slug' => '', 'description' => ''],
['category' => 'ভ্রমণ ও প্রবাস', 'category_slug' => '', 'description' => ''],
['category' => 'ভাষা ও অভিধান', 'category_slug' => '', 'description' => ''],
['category' => 'মুক্তিযুদ্ধভিত্তিক সাহিত্য', 'category_slug' => '', 'description' => ''],
['category' => 'মুক্তিযুদ্ধের ইতিহাস', 'category_slug' => '', 'description' => ''],
['category' => 'মেডিকেল', 'category_slug' => '', 'description' => ''],
['category' => 'রহস্য,গোয়েন্দা,ভৌতিক,থ্রিলার ও অ্যাডভেঞ্চার', 'category_slug' => '', 'description' => ''],
['category' => 'রাজনীতি', 'category_slug' => '', 'description' => ''],
['category' => 'রান্না ,খাদ্য ও পুষ্টি', 'category_slug' => '', 'description' => ''],
['category' => 'শিশু কিশোর বই', 'category_slug' => '', 'description' => ''],
['category' => 'সংগীত চলচ্চিত্র ও বিনোদন', 'category_slug' => '', 'description' => ''],
['category' => 'সমাজ,সভ্যতা ও সংস্কৃতি', 'category_slug' => '', 'description' => ''],
['category' => 'সংগীত', 'category_slug' => '', 'description' => ''],
['category' => 'মুসলিম সভ্যতা ও সংস্কৃতি', 'category_slug' => '', 'description' => ''],
['category' => 'বাংলাদেশ', 'category_slug' => '', 'description' => ''],
['category' => 'অঞ্চলভিত্তিক', 'category_slug' => '', 'description' => ''],
['category' => 'জীবন,জীবিকা ও সংস্কৃতি', 'category_slug' => '', 'description' => ''],
['category' => 'প্রাচীন সভ্যতা', 'category_slug' => '', 'description' => ''],
['category' => 'সায়েন্স ফিকশন', 'category_slug' => '', 'description' => ''],
['category' => 'স্বাস্থ্য,পরিচর্যা ও রোগ নিরাময়', 'category_slug' => '', 'description' => '']
];
